### ISSUE TITLE
propose renaming to iso8601

### ISSUE THREAD

**Issue by pmetzger** [sagotch/ISO8601.ml#16]
Normally we tend not to name libraries something like `foo.ml` but rather `foo`. Perhaps this repository (and the package) should simply be `iso8601`?

**Comment by c-cube** [comment]
of course I forgot, but lo, it's such a bad idea to rename repos. It breaks previous releases.

**Comment by pmetzger** [comment]
But this new repo hasn't had a release yet, yes?

**Comment by c-cube** [comment]
No, but renaming repos changes the hash of the github-generated release tarballs :(

**Comment by pmetzger** [comment]
Okay, that's gross.
