### ISSUE TITLE
ISO8601 Basic String

### ISSUE THREAD

**Issue by alexleighton** [sagotch/ISO8601.ml#2]
ISO8601 defines a "basic" format which contains none of the human-readable separators. See [here](http://en.wikipedia.org/wiki/ISO_8601#General_principles), third bullet point.

I'm working on a DynamoDB client for OCaml ([ocaml-dynamodb](https://github.com/alexleighton/ocaml-dynamodb)). Making an AWS client requires the ability to create an ISO8601 "basic" formatted datetime: see [making HTTP requests](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/MakingHTTPRequests.html), second bullet point of HTTP Header Contents.

If you have the bandwidth, I'd like to request a function like string_of_datetime_basic or string_of_datetime_short. Java's Joda-Time library uses ["basic"](http://joda-time.sourceforge.net/apidocs/org/joda/time/format/ISODateTimeFormat.html#basicDateTime()). If you don't have the bandwidth, I'm happy to craft a pull request.

**Comment by sagotch** [comment]
I agree, and it was actually a planned feature, but what was planned was actually more a kind of
printf format (with shortener function) like `pp_datetime` for `%Y-%M-%DT%h:%m:%s%z` and `pp_datetime_basic` for `%Y%M%DT%h%m%s%z`.

**Comment by alexleighton** [comment]
Thank you!

**Comment by sagotch** [comment]
No problem. Version 0.2.0 should be available in opam soon.
